#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raising a NameError exception, but with a message this time."""
    raise NameError(message)
